//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class apuesta
    {
        public int id_apuesta { get; set; }
        public int id_Ruleta { get; set; }
        public int id_Usuario { get; set; }
        public int valorApuesta { get; set; }
        public int numero { get; set; }
        public int id_color { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Ruletas Ruletas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
